name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  # Variables de entorno globales
  PHP_VERSION: '8.2'
  NODE_VERSION: '18'

jobs:
  # ============================================
  # JOB 1: TESTS Y CALIDAD
  # ============================================
  test:
    name: Tests & Quality Checks
    runs-on: ubuntu-latest

    # Servicios (MySQL para tests)
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para métricas DORA

      # 2. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, dom, filter, gd, json
          coverage: xdebug
          tools: composer:v2

      # 3. Cache de Composer
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # 4. Instalar dependencias
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-progress

      # 5. Preparar entorno
      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache

      # 6. Ejecutar migraciones
      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: password
        run: php artisan migrate --force

      # 7. Ejecutar tests
      - name: Execute tests (Unit and Feature)
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: password
        run: php artisan test --parallel

      # 8. Análisis estático (si tienes PHPStan)
      - name: Run PHPStan
        run: |
          if [ -f "phpstan.neon" ]; then
            ./vendor/bin/phpstan analyse --memory-limit=2G
          else
            echo "PHPStan not configured, skipping..."
          fi
        continue-on-error: true

      # 9. Code Style (Laravel Pint)
      - name: Check Code Style
        run: |
          if [ -f "pint.json" ]; then
            ./vendor/bin/pint --test
          else
            echo "Pint not configured, skipping..."
          fi
        continue-on-error: true

  # ============================================
  # JOB 2: DEPLOY (solo en main)
  # ============================================
  deploy:
    name: Deploy to Production
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Aquí iría tu proceso de deploy real
      # Por ahora simulamos
      - name: Deploy to Server
        run: |
          echo "🚀 Deploying to production..."
          echo "📦 Branch: ${{ github.ref_name }}"
          echo "📝 Commit: ${{ github.sha }}"
          # Aquí pondrías tus comandos reales de deploy:
          # - SSH a tu servidor
          # - Pull del código
          # - Composer install
          # - Migraciones
          # - etc.
          sleep 5
          echo "✅ Deploy completed!"

      # ============================================
      # MÉTRICAS DORA
      # ============================================

      # MÉTRICA 1: Deployment Frequency
      - name: 📊 DORA - Record Deployment
        if: success()
        run: |
          curl -X POST ${{ secrets.APP_URL }}/api/metrics/deployment \
            -H "Content-Type: application/json" \
            -H "X-API-Key: ${{ secrets.METRICS_API_KEY }}" \
            -d '{
              "tool": "github-actions",
              "timestamp": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'",
              "branch": "'"${{ github.ref_name }}"'",
              "commit": "'"${{ github.sha }}"'",
              "status": "success"
            }'

      # MÉTRICA 2: Lead Time for Changes
      - name: 📊 DORA - Calculate Lead Time
        if: success()
        run: |
          COMMIT_TIME=$(git show -s --format=%cI ${{ github.sha }})
          DEPLOY_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)

          COMMIT_EPOCH=$(date -d "$COMMIT_TIME" +%s)
          DEPLOY_EPOCH=$(date -d "$DEPLOY_TIME" +%s)
          LEAD_TIME=$((DEPLOY_EPOCH - COMMIT_EPOCH))

          echo "⏱️  Lead Time: $LEAD_TIME seconds ($((LEAD_TIME / 60)) minutes)"

          curl -X POST ${{ secrets.APP_URL }}/api/metrics/leadtime \
            -H "Content-Type: application/json" \
            -H "X-API-Key: ${{ secrets.METRICS_API_KEY }}" \
            -d '{
              "tool": "github-actions",
              "commit": "'"${{ github.sha }}"'",
              "commit_time": "'"$COMMIT_TIME"'",
              "deploy_time": "'"$DEPLOY_TIME"'",
              "lead_time_seconds": '$LEAD_TIME'
            }'

      # MÉTRICA 3: Change Failure Rate (registro exitoso)
      - name: 📊 DORA - Record Success
        if: success()
        run: |
          curl -X POST ${{ secrets.APP_URL }}/api/metrics/deployment-result \
            -H "Content-Type: application/json" \
            -H "X-API-Key: ${{ secrets.METRICS_API_KEY }}" \
            -d '{
              "tool": "github-actions",
              "timestamp": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'",
              "commit": "'"${{ github.sha }}"'",
              "status": "success",
              "is_failure": false
            }'

      # MÉTRICA 3: Change Failure Rate (registro de fallo)
      - name: 📊 DORA - Record Failure
        if: failure()
        run: |
          curl -X POST ${{ secrets.APP_URL }}/api/metrics/deployment-result \
            -H "Content-Type: application/json" \
            -H "X-API-Key: ${{ secrets.METRICS_API_KEY }}" \
            -d '{
              "tool": "github-actions",
              "timestamp": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'",
              "commit": "'"${{ github.sha }}"'",
              "status": "failure",
              "is_failure": true
            }'

      # MÉTRICA 4: MTTR - Registrar incidente si falla
      - name: 📊 DORA - Record Incident
        if: failure()
        run: |
          curl -X POST ${{ secrets.APP_URL }}/api/metrics/incident \
            -H "Content-Type: application/json" \
            -H "X-API-Key: ${{ secrets.METRICS_API_KEY }}" \
            -d '{
              "tool": "github-actions",
              "incident_id": "'"${{ github.run_id }}"'",
              "start_time": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'",
              "commit": "'"${{ github.sha }}"'",
              "status": "open"
            }'

      # MÉTRICA 4: MTTR - Resolver incidente si el deploy anterior falló pero este es exitoso
      - name: 📊 DORA - Resolve Previous Incident
        if: success()
        run: |
          curl -X POST ${{ secrets.APP_URL }}/api/metrics/incident/resolve \
            -H "Content-Type: application/json" \
            -H "X-API-Key: ${{ secrets.METRICS_API_KEY }}" \
            -d '{
              "tool": "github-actions",
              "resolution_time": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'"
            }'

